Issue 23 Smtp testing
linagora/james-gatling pull request #28
Opened 2016-10-14 14:36 UTC by chibenwa

Code have been adapted from [OBM load test SMTP](https://ci-obm.linagora.com/stash/projects/OBMTEST/repos/obmtest/browse/src/main/scala/org/obm/gatling/protocol/smtp)

There are much changes between 2.2.0 and 2.0.0.

I observe a rate of ~10 mail / sec out of the mailqueue on my computer.

![gatling_smtp](https://cloud.githubusercontent.com/assets/6928740/19391276/2d3b0992-922c-11e6-990d-b937c22ad7e3.png)

2016-10-14 14:50 UTC, mbaechler requested changes

2016-10-14 14:50 UTC, mbaechler commented on src/main/scala-2.11/org/apache/james/gatling/smtp/SmtpAction.scala
> +    var errorMessage: Option[String] = None
using Try or Either would avoid using var

2016-10-14 14:50 UTC, mbaechler commented on src/main/scala-2.11/org/apache/james/gatling/smtp/SmtpAction.scala
> +    val reqStart = System.currentTimeMillis()
start should be taken before  `email.send()`

2016-10-14 14:50 UTC, mbaechler commented on src/test/scala-2.11/org/apache/james/gatling/smtp/scenari/NoAuthenticationNoEncryptionScenario.scala
> +  setUp(scn.inject(atOnceUsers(UserCount))).protocols(smtp)
you can use a ratelimiter to manage a constant rate

2016-10-14 15:06 UTC, chibenwa commented on src/test/scala-2.11/org/apache/james/gatling/smtp/scenari/NoAuthenticationNoEncryptionScenario.scala
> +  setUp(scn.inject(atOnceUsers(UserCount))).protocols(smtp)
I prefer **rampUsers over** which allow me to specify this without having to do the maths, but OK, implemented

2016-10-14 15:10 UTC, mbaechler commented on src/test/scala-2.11/org/apache/james/gatling/smtp/scenari/NoAuthenticationNoEncryptionScenario.scala
> +  setUp(scn.inject(atOnceUsers(UserCount))).protocols(smtp)
nope, it's not the same thing : ramp user will ramp users, but a user can send requests for some time, you don't manage the number of concurrent users because it depends on latency, etc. the rate limit ensure a ... rate limit, whatever the number of user is.

2016-10-14 15:21 UTC, chibenwa commented on src/main/scala-2.11/org/apache/james/gatling/smtp/SmtpAction.scala
> +    val reqStart = System.currentTimeMillis()
Ok

2016-10-14 15:21 UTC, chibenwa commented on src/main/scala-2.11/org/apache/james/gatling/smtp/SmtpAction.scala
> +    var errorMessage: Option[String] = None
I simplified code a lot using case class

2016-10-14 15:30 UTC, chibenwa commented
By the way : 

![gc](https://cloud.githubusercontent.com/assets/6928740/19393159/e08345ee-9233-11e6-9f03-9597c425cbcf.png)

It's very clear here we are having GC troubbles somewhere (just like JMAP sendMessage pointed it out)

2016-10-14 16:09 UTC, mbaechler commented on src/main/scala-2.11/org/apache/james/gatling/smtp/SmtpAction.scala
> +case class ExecutionReport(errorMessage: Option[String], status: Status)
come on, you recreated Try !

2016-10-14 16:09 UTC, mbaechler commented on src/test/scala-2.11/org/apache/james/gatling/smtp/scenari/NoAuthenticationNoEncryptionScenario.scala
> +  setUp(scn.inject(nothingFor(10 seconds), rampUsers(UserCount) over(10 seconds))).protocols(smtp)
it's not what I meant, here is an extract of another project of mine : 

```
.maxDuration(5 minutes)
    .throttle(
    reachRps(100) in (10 seconds),
    holdFor(3 minute)
```

2016-10-17 08:56 UTC, chibenwa commented on src/main/scala-2.11/org/apache/james/gatling/smtp/SmtpAction.scala
> +case class ExecutionReport(errorMessage: Option[String], status: Status)
Ok

2016-10-17 08:57 UTC, chibenwa commented on src/test/scala-2.11/org/apache/james/gatling/smtp/scenari/NoAuthenticationNoEncryptionScenario.scala
> +  setUp(scn.inject(nothingFor(10 seconds), rampUsers(UserCount) over(10 seconds))).protocols(smtp)
If I do so, I have stack overflow after 45 seconds

2016-10-17 09:00 UTC, mbaechler commented on src/test/scala-2.11/org/apache/james/gatling/smtp/scenari/NoAuthenticationNoEncryptionScenario.scala
> +  setUp(scn.inject(nothingFor(10 seconds), rampUsers(UserCount) over(10 seconds))).protocols(smtp)
how is that possible ? What is the stack ?

2016-10-17 09:17 UTC, chibenwa commented
```
at org.apache.james.gatling.smtp.SmtpAction.execute(SmtpAction.scala:32)
	at io.gatling.core.action.Action$class.$bang(Action.scala:35)
	at org.apache.james.gatling.smtp.SmtpAction.io$gatling$core$action$ChainableAction$$super$$bang(SmtpAction.scala:14)
	at io.gatling.core.action.ChainableAction$class.$bang(Action.scala:60)
	at org.apache.james.gatling.smtp.SmtpAction.$bang(SmtpAction.scala:14)
	at io.gatling.core.action.InnerLoop.execute(Loop.scala:66)
	at io.gatling.core.action.Action$class.$bang(Action.scala:35)
	at io.gatling.core.action.InnerLoop.io$gatling$core$action$ChainableAction$$super$$bang(Loop.scala:41)
	at io.gatling.core.action.ChainableAction$class.$bang(Action.scala:60)
	at io.gatling.core.action.InnerLoop.$bang(Loop.scala:41)
	at io.gatling.core.action.Loop.io$gatling$core$action$Loop$$$anonfun$1(Loop.scala:38)
	at io.gatling.core.action.Loop.io$gatling$core$action$Loop$$$anonfun$1$adapted(Loop.scala:38)
	at io.gatling.core.action.ExitableAction$.exitOrElse(BlockExit.scala:125)
	at io.gatling.core.action.Loop.execute(Loop.scala:38)
	at io.gatling.core.action.Action$class.$bang(Action.scala:35)
	at io.gatling.core.action.Loop.$bang(Loop.scala:30)
	at org.apache.james.gatling.smtp.SmtpAction.execute(SmtpAction.scala:32)
```

2016-10-17 13:26 UTC, mbaechler commented
could you mind asking the community about that ?

2016-10-17 13:26 UTC, mbaechler approved these changes

2016-10-17 14:37 UTC, chibenwa commented
I asked on their Google group : https://groups.google.com/forum/#!topic/gatling/u3J7Prsz6Xo

2016-10-18 11:55 UTC, aduprat approved these changes

2016-10-18 12:02 UTC, merged